import type { Company } from "@/lib/types";

export const companies: Record<string, Company> = {
  BLS: {
    ticker: "BLS",
    name: "BLS International Services",
    exchange: "BSE",
    sector: "Specialised Services",
    industry: "Visa, Passport & Consular Services",
    marketCap: 13420_00_00_000,
    lastPrice: 326.45,
    change: -4.82,
    volume: 8_42_15_300,
    concentrationRisk: 78,
    signalScore: 92,
    about:
      "Outsourcing partner for diplomatic missions worldwide — visa, passport, citizen services and consular support across 70+ countries.",
  },
  BEL: {
    ticker: "BEL",
    name: "Bharat Electronics",
    exchange: "NSE",
    sector: "Defence",
    industry: "Defence Electronics",
    marketCap: 218450_00_00_000,
    lastPrice: 298.7,
    change: 1.34,
    volume: 1_24_82_500,
    concentrationRisk: 42,
    signalScore: 64,
    about:
      "Navratna defence PSU producing radars, missile electronics, communication systems and electronic warfare equipment for MoD.",
  },
  HAL: {
    ticker: "HAL",
    name: "Hindustan Aeronautics",
    exchange: "NSE",
    sector: "Defence",
    industry: "Aerospace & Defence",
    marketCap: 312880_00_00_000,
    lastPrice: 4682.5,
    change: 0.86,
    volume: 38_24_120,
    concentrationRisk: 58,
    signalScore: 71,
    about:
      "Aircraft manufacturer producing Tejas, Dhruv, LCH and upgrading Sukhoi-30 MKI fleet for the Indian Air Force.",
  },
  IRCON: {
    ticker: "IRCON",
    name: "IRCON International",
    exchange: "NSE",
    sector: "Infrastructure",
    industry: "Railway EPC",
    marketCap: 18650_00_00_000,
    lastPrice: 198.4,
    change: -0.42,
    volume: 84_15_320,
    concentrationRisk: 64,
    signalScore: 48,
    about:
      "Mini-Ratna PSU specialised in railway construction, dedicated freight corridor work, and overseas rail infrastructure.",
  },
  LT: {
    ticker: "LT",
    name: "Larsen & Toubro",
    exchange: "NSE",
    sector: "Infrastructure",
    industry: "Engineering & Construction",
    marketCap: 482310_00_00_000,
    lastPrice: 3514.2,
    change: 1.12,
    volume: 24_38_510,
    concentrationRisk: 28,
    signalScore: 56,
    about:
      "Multinational EPC conglomerate — defence, infrastructure, hydrocarbons, power, water and shipbuilding.",
  },
  RVNL: {
    ticker: "RVNL",
    name: "Rail Vikas Nigam",
    exchange: "NSE",
    sector: "Infrastructure",
    industry: "Railway Construction",
    marketCap: 84120_00_00_000,
    lastPrice: 403.85,
    change: 2.18,
    volume: 1_62_34_810,
    concentrationRisk: 52,
    signalScore: 59,
    about:
      "Implementation arm of Indian Railways — rail line doubling, electrification, new line construction, and metro rail projects.",
  },
};

export const companyList = Object.values(companies);
