import type { Tender } from "@/lib/types";

// Today is treated as 2026-05-19. Dates are spread across recent past and upcoming 60 days.
export const tenders: Tender[] = [
  {
    id: "tender-bls-morocco",
    refNo: "MEA/CONSULAR/2026/MOR-014",
    title: "Provision of Visa & Passport Outsourcing Services — Embassy of India, Rabat (Morocco)",
    buyer: "Ministry of External Affairs",
    ministry: "MEA",
    description:
      "Selection of agency for outsourcing of visa, passport and consular services at the Embassy of India in Rabat including biometric enrolment, document attestation and citizen service kiosks across Casablanca and Tangier.",
    estimatedValue: 84_50_00_000,
    sectorTagIds: ["visa-passport"],
    watchedCompanies: ["BLS"],
    knownBidders: ["BLS International", "VFS Global", "TLScontact"],
    competitorBidders: ["VFS Global", "TLScontact"],
    milestones: [
      { type: "bid_submission", date: "2026-04-22T17:00:00+05:30", description: "Last date for online bid upload" },
      { type: "technical_evaluation", date: "2026-05-08T11:00:00+05:30", description: "Opening of technical bids" },
      {
        type: "financial_bid_opening",
        date: "2026-05-26T11:30:00+05:30",
        description: "Opening of financial bids (D-Day)",
      },
    ],
    status: "evaluation",
    publishedAt: "2026-03-12T10:00:00+05:30",
    sourcePortal: "CPPP",
    sourceUrl: "https://eprocure.gov.in/eprocure/app",
    matchScore: 96,
  },
  {
    id: "tender-bls-saudi",
    refNo: "MEA/CONSULAR/2026/KSA-008",
    title: "Outsourced Visa Application Centres — Embassy of India, Riyadh & Consulate Jeddah",
    buyer: "Embassy of India, Riyadh",
    ministry: "MEA",
    description:
      "Operation of visa application centres in Riyadh, Jeddah and Dammam for the next 5-year period, including biometric capture, document handling and labour-visa processing.",
    estimatedValue: 215_00_00_000,
    sectorTagIds: ["visa-passport"],
    watchedCompanies: ["BLS"],
    knownBidders: ["BLS International", "VFS Global"],
    competitorBidders: ["VFS Global"],
    milestones: [
      { type: "bid_submission", date: "2026-05-30T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-06-12T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-06-25T11:30:00+05:30" },
    ],
    status: "bidding_open",
    publishedAt: "2026-04-18T10:00:00+05:30",
    sourcePortal: "CPPP",
    matchScore: 94,
  },
  {
    id: "tender-bel-radar",
    refNo: "MoD/IAF/RADAR/2026/77",
    title: "Procurement of 35 Light Mountain Radar Systems — Indian Air Force",
    buyer: "Ministry of Defence",
    ministry: "MoD",
    description:
      "Supply, installation and 7-year MRO support for 35 light mountain radar systems for forward IAF bases in the Northern Command sector. Includes integrated communication suite and electronic counter-counter measure (ECCM).",
    estimatedValue: 2480_00_00_000,
    sectorTagIds: ["defence-electronics"],
    watchedCompanies: ["BEL"],
    knownBidders: ["Bharat Electronics", "Tata Advanced Systems"],
    competitorBidders: ["Tata Advanced Systems"],
    milestones: [
      { type: "bid_submission", date: "2026-04-30T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-05-22T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-06-09T11:30:00+05:30" },
    ],
    status: "evaluation",
    publishedAt: "2026-02-28T10:00:00+05:30",
    sourcePortal: "CPPP",
    matchScore: 92,
  },
  {
    id: "tender-hal-engine",
    refNo: "MoD/IAF/ENGINE-MRO/2026/12",
    title: "Sukhoi-30 MKI AL-31FP Engine Overhaul Programme — 5 Year Contract",
    buyer: "Indian Air Force",
    ministry: "MoD",
    description:
      "Comprehensive overhaul and major repair contract for AL-31FP engines fitted on the Sukhoi-30 MKI fleet over the next 5 years, including spares supply and on-site technical support.",
    estimatedValue: 6850_00_00_000,
    sectorTagIds: ["aerospace"],
    watchedCompanies: ["HAL"],
    knownBidders: ["Hindustan Aeronautics"],
    milestones: [
      { type: "bid_submission", date: "2026-05-12T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-05-30T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-06-18T11:30:00+05:30" },
    ],
    status: "evaluation",
    publishedAt: "2026-03-04T10:00:00+05:30",
    sourcePortal: "CPPP",
    matchScore: 89,
  },
  {
    id: "tender-rvnl-doubling",
    refNo: "RAIL/CR/DBL/2026/MUM-PUNE-2",
    title: "Track Doubling Mumbai–Pune Section Phase II — Civil + Electrification",
    buyer: "Ministry of Railways",
    ministry: "MoR",
    description:
      "EPC contract for doubling of the Mumbai–Pune railway section Phase II including civil works, OHE electrification and signalling upgrade across 92 km.",
    estimatedValue: 3120_00_00_000,
    sectorTagIds: ["railway-epc"],
    watchedCompanies: ["RVNL", "IRCON", "LT"],
    knownBidders: ["RVNL", "IRCON", "L&T", "KEC International"],
    competitorBidders: ["KEC International"],
    milestones: [
      { type: "bid_submission", date: "2026-05-25T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-06-10T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-06-22T11:30:00+05:30" },
    ],
    status: "bidding_open",
    publishedAt: "2026-04-02T10:00:00+05:30",
    sourcePortal: "CPPP",
    matchScore: 91,
  },
  {
    id: "tender-ircon-metro",
    refNo: "MMRC/CIVIL/UG-08/2026",
    title: "Mumbai Metro Line 6 — Underground Civil Package UG-08 (3.4 km)",
    buyer: "MMRC (Mumbai Metro Rail Corporation)",
    description:
      "Design and construction of underground civil package UG-08 of Mumbai Metro Line 6 covering 3.4 km of tunnels and 4 stations using EPBM tunnel boring methodology.",
    estimatedValue: 1840_00_00_000,
    sectorTagIds: ["infra-epc", "railway-epc"],
    watchedCompanies: ["IRCON", "LT"],
    knownBidders: ["IRCON", "L&T", "Afcons Infrastructure"],
    milestones: [
      { type: "bid_submission", date: "2026-06-04T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-06-20T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-07-05T11:30:00+05:30" },
    ],
    status: "upcoming",
    publishedAt: "2026-04-25T10:00:00+05:30",
    sourcePortal: "State",
    matchScore: 88,
  },
  {
    id: "tender-bls-uae",
    refNo: "MEA/CONSULAR/2025/UAE-019",
    title: "Outsourced Visa & Passport Services — UAE Mission (Awarded)",
    buyer: "Ministry of External Affairs",
    ministry: "MEA",
    description:
      "Five-year outsourcing contract for visa and passport services across Indian missions in UAE. Result: Alhind Group selected as L1 bidder after financial bid opening on 5 May 2026.",
    estimatedValue: 320_00_00_000,
    sectorTagIds: ["visa-passport"],
    watchedCompanies: ["BLS"],
    knownBidders: ["BLS International", "Alhind Group", "VFS Global"],
    competitorBidders: ["Alhind Group", "VFS Global"],
    milestones: [
      { type: "bid_submission", date: "2026-03-28T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-04-18T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-05-05T11:30:00+05:30" },
      { type: "result_announcement", date: "2026-05-08T16:00:00+05:30", description: "Alhind Group awarded contract" },
    ],
    status: "awarded",
    publishedAt: "2026-01-15T10:00:00+05:30",
    sourcePortal: "CPPP",
    matchScore: 99,
  },
  {
    id: "tender-bel-comms",
    refNo: "MoD/NAVY/COMMS/2026/41",
    title: "Secure Naval Communication Suites — 12 Frigates",
    buyer: "Indian Navy",
    ministry: "MoD",
    description:
      "Supply and integration of secure software-defined radio communication suites across 12 Project-17B frigates, including encrypted satcom and tactical data link.",
    estimatedValue: 1240_00_00_000,
    sectorTagIds: ["defence-electronics"],
    watchedCompanies: ["BEL"],
    knownBidders: ["Bharat Electronics", "Honeywell India", "Thales India"],
    competitorBidders: ["Honeywell India", "Thales India"],
    milestones: [
      { type: "bid_submission", date: "2026-06-10T17:00:00+05:30" },
      { type: "technical_evaluation", date: "2026-06-28T11:00:00+05:30" },
      { type: "financial_bid_opening", date: "2026-07-12T11:30:00+05:30" },
    ],
    status: "upcoming",
    publishedAt: "2026-05-02T10:00:00+05:30",
    sourcePortal: "GeM",
    matchScore: 87,
  },
];

export const tendersById = Object.fromEntries(tenders.map((t) => [t.id, t]));
